# .readthedocs.yaml
# Read the Docs (RTD) configuration file for neoads
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# This file is used by RTD to build the documentation version that appears
# at: https://neoads.readthedocs.io/en/latest

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

# The requirements.txt file specified in this section lists all packages 
# required to build *just* the documentation for pymotifcounter
# For more information please see:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: doc/requirements.txt
